---
title: GoDaddy Marketing Planner
timezone: UTC
collections:
  hashtags:
    title: Hashtags
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: A curated collection of ideas for your next social post.
baseurl: '/'
url: 'http://gomarketingplanner.co/'
twitter_username: posty_sike
github_username: posty_sike
plugins:
- jekyll-feed
google_analytics: false
